create table questions(
id serial PRIMARY KEY,
question varchar(300),
correct varchar (100),
wrong_1 varchar(100),
	wrong_2 varchar(100),
	wrong_3 varchar(100)
)

select * from questions

insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('Whats the largest desert in the world?','Antarctica','Sahara','Arabian','Gobi')

insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('Who sang the title song for the latest Bond film, No Time to die','Adele','Sam Smith','Billie Eilish','Rihanna')
insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('What company makes the Xperia model of smartphone?','Sony','Apple','Nokia','Google')
insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('Which city is home to the Brandenburg Gate','Berlin','Zurich','Paris','Vienna')
insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('Where was the first example of paper money used?','China','Turkey','England','Greece')
insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('Who is generally considered the inventor of the motor car?','Karl Benz','Charles Darwin','Henry M. Leland','Henry_Ford')
insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('If you were looking at Iguazu Falls, on what continent would you be?','South America','Europe','Africa','Asia')
insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('What number was the Apollo mission that successfully put a man on the moon for the first time in human history?','Apollo 11','Apollo 12','Apollo 13','Apollo 14')
insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('Which of the following languages has the longest alphabet?','Russian','Arabic','Israeli','Greek')
insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('','Roger Daltrey','Darwin Nunez','Robert Plant','Don Henley')
insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('What spirit is used in making a Tom Collins?','Gin','Rum','Vodka','Apple Juice')
insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('The fear of insects is known as what?','Entomophobia','Anti Insect Phobia','Ailurophobia','Arachnophobia')
insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('What was the name of the Franco-British supersonic commercial plane that operated from 1976-2003?','Concorde','Boeing 24/7','Mirage','Accord')
insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('Which horoscope sign is a fish?','Pisces ','Gemini','Cancer','Aquarius')
insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('What is the largest US state (by landmass)?','Alaska','Washington DC','Texas','California')
insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('Which app has the most total users?','Instagram','Facebook','Snapchat','TikTok')
insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('Which Game of Thrones character is known as the Young Wolf?','Robb Stark','John Cena','Arya Stark','Sansa Stark')
insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('What city hosted the 2002 Olympic Games?','Sydney','Beijing','London','Tokyo')
insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('How many plays do people (generally) believe that Shakespeare wrote?','37','17','47','27')
insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('Which of the following was considered one of the Seven Ancient Wonders?','Colossus of Rhodes','London Bridge','Colosseum','Great Wall of China')
insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('Who directed the Academy Award-winning movie, Gladiator?','Ridley Scott','James Cameron','Borris Johnson','Steven Soderbergh')
insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('How long did dinosaurs live on the earth?','150-200 million years','17 years','100-150 million years','200+ million years')
insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('What Italian city is famous for its system of canals?','Venice','Victoria','Naples','Rome')
insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('What is the strongest muscle in the human body?','Jaw','Phalanges','Heart','Glutes')
insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('What is the longest-running Broadway show ever?','The Phantom of the Opera','Les Miserable','Dispicable Me','The Lion King')
insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('Where was tea invented?','China','USA','Japan','England')
insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('Where was the earliest documented case of the Spanish flu?','USA','China','Mexico','Spain')
insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('Which of the following languages is NOT driven from Latin?','English','portuguese','Chinese','French')
insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('Arnold Schwarzenegger was married to a member of what famous US political family?','The Kennedys','The Weasley's,'The Bushes','The Rockefellers')
insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('Who was elected President of the United States in 2017?','Donald Trupm','Barack Obama','Donald Duck','George Bush')
insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('When did Jonas Brothers make their comeback to the music world?','2019','2005','1978','2020')
insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('What is the national language of Canada?','Dutch',Giberish,'English','French')
insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('What is the national animal of Pakistan?','Markhor','Lion','Peacock','Timon & Pubma')
insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('A la Crecy is a French dish made of what?','Carrots','Potatoes','Turnips','Apples')
insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('What native country is Brazil?','North America','West America','East America','South America')
insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('Which core ingredient is important to cook a savory dish?','Salt','Pickle Juice','Butter','Sugar')
insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('Brazil is the biggest producer of?','Coffee','Oil','Guns','Rice')
insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('Saudi Arabia is the biggest producer of?','Oil','Coffee','Coal','Salt')
insert into questions(question,correct,wrong_1,wrong_2,wrong_3)
values('Which country is infamously known as Arch Rival of Pakistan?','India','Germany','England','Afghanistan')